### ISSUE TITLE
Hide the study doc form input on the submission start page

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#1120]
### Inspiration

See #1034 and #1040

### Description

1. Add a "page" context variable to the return from `form_valid` #1093
2. Add a tab bar to the template that highlights the current "page" (defaulting to "Start"). #1093
3. Add a "Next" link (that appears as a button and temporarily always is shown) next to the "Download" button. Clicking next advances the tab highlight and doesn't process the form (and clicking the tab jumps to that page). #1093
4. Modify the template to hide the study doc form input when the page is the "Start" page
5. Modify the template to not render the entire form when the page is "Fill In", and render the fill-in instructions and "Next" button instead.
6. Modify the template to hide the peak annotations input when the page is the "Validate" page.
7. Modify the template to not render the entire form on the "Submit" page and render the link to the google form (and instructions) instead.
8. Modify the template to only show the "Next" button on the Start page when results are presented
9. Modify the template to show the "Next" button on the Validate page when results are presented (and present it as "Skip" when not displayed with results)
10. Make the "Upload" link in the nav bar go directly to the submission page (leaving the upload page for now)

### Alternatives

None

### Dependencies

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking
