### ISSUE TITLE
Display summary search result data

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#159]
### Feature Inspiration

Feedback from Michael during the meeting on 7/28/2021, which was documented in [his notes](https://docs.google.com/document/d/1HCdqFgIDjGeaA8p1M8ElZhWuwxuczVvfwdydhuhLPUo/edit).

### Feature Description

Michael described a summary table (above?) the search results that lists customizable stats, like number of unique values in selected columns or a stat showing number of values above (or below?) some threshold.

### Alternatives Considered

I suggested an alternative: show a count of unique values in the column headers and upon hover:

- text column: show a list of unique values (if some amount fewer than the number of results) in a tooltip
- numeric column: show a rudimentary histogram in a tooltip

### Comment

The histogram in the alternative suggestion would be in lieu of a user-selected threshold.

-----

### ToDo

- [x] Write tests
- [x] Test with hefty data to make sure the work-around code doesn't slow the interface on big queries (this is in process - as I'm loading data from the dev site in my sandbox)
- [ ] Try out counting cached properties using the current counting code (which was a work-around of lacking django support)
- [ ] Try out filtering cached properties by resurrecting a portion of the old (removed) refilter code.

### Assumptions

none

### Requirements

- [x] Keeps advanced search fast
- [x] Displays selected stats in a small table
- [x] Shows top 10 values and their counts for each stat field (truncate long strings, but show in a tooltip)
- [x] Shows a count of unique values for each stat field
- [x] Shows the filter criteria
- [x] When a filter is present, counts are of records meeting the criteria, not unique values meeting the criteria
- [x] Computing stats only happens when the stats button first clicked.  Subsequent clicks just collapse and show
- [x] Computed stats follow paging results (so they don't have to be recomputed on any page)
- [x] Stats start out collapsed (unless stats button was clicked)
- [x] Wait message appears when first clicking the stats button
- [x] Minimize stats computing time
- [x] Unique counts work when split_rows is true and duplicate root table records exist

### Limitations

- Computing stats can take time for large results

### Affected/Changed Components

- pager.py
- views.py
- compositeviews.py
- customtags.py
- forms.py
- pagination.html
- stats.html

#### GUI Change description

A table with 3 columns appears after clicking a new "Stats" button top right of the results.

#### Code Change Description *(Pseudocode optional)*

Included a stats.html template and used bootstrap's collapse feature.  Incorporated the show stats request into the paging form.  Stats config is in a new stats datamember in each compositeviews derived class and performQuery takes a boolean (default false) as to whether to take on stats to the request.

#### Tests

Existing tests have been fixed, but I've yet to plan out new tests...

**Comment by hepcat72** [comment]
Just finished a proof of concept on this.  It's not pretty yet, but it works.  It cannot handle "cached_property" fields however. That needs to be solved at a deeper level...
<img width="1427" alt="stats_poc" src="https://user-images.githubusercontent.com/2300532/159084630-34808f50-7da4-49de-adc6-3d6642da29cc.png">

Note that the values listed in the Example column are the top 10 field values (in tuples) in descending order of number of occurrences.

Take a look @mneinast and let me know what you think data-wise.  Note, the corrected abundances are those larger than 0.1.  I just haven't implemented a display of the filtering criteria yet.

**Comment by hepcat72** [comment]
OK.  Made it pretty & collapsible.  Cannot yet implement stats for cached_property fields.  Also still haven't added the filter yet, like the corrected abundance threshold.

![adv-srch-stats-demo](https://user-images.githubusercontent.com/2300532/159134333-2d6ef52b-89f4-455f-8e55-ff98ceb47a9b.gif)

**Comment by hepcat72** [comment]
OK, just added a very simple (limited support) display of the filter criteria in the feature column.

**Comment by mneinast** [comment]
This is fantastic!  Showing the unique values is super helpful.  I will look at this in more detail soon.

**Comment by mneinast** [comment]
are the cached property fields things like genotype?  I think the most important stats for unique values are this metadata - so that the researcher can have a better sense of what they're seeing.

overall this is very cool and i think super useful!

**Comment by hepcat72** [comment]
I can add fields. The "cached property" fields are the ones whose value would change if more data was added or removed or changed. Things like enrichment fraction, normalized labeling, etc. I included everything in your example (linked in the issue) except those that are cached properties. I can add genotype or other fields if you like. It's easy to change.

I was thinking that a future version could allow the user to include selected fields...

**Comment by hepcat72** [comment]
Would have created a PR already, except I ran into an issue in the tests.  Django supports my implementation, but only in certain cases.  Apparently, if you supply `Count(...)` to `.annotate()`, after having used `.distinct(<with field names>)`, *and* there are duplicate root table records, you get this misleading error:

```
NotImplementedError: annotate() + distinct(fields) is not implemented
```

It is implemented, because I use `.annotate()` with `distinct(fields)` in another PR.  So the only different is aggregation using `Count(...)`.  *That's* what's unsupported.

And in fact, this gave me an idea.  I realized, given the code I wrote to do those counts, that it should be able to also implement counting (and filters) of "cached properties" this way too, so I may try it out and see what happens.

Current remaining todo:

- [ ] Write tests
- [ ] Test with hefty data to make sure the work-around code doesn't slow the interface on big queries (this is in process - as I'm loading data from the dev site in my sandbox)
- [ ] Try out counting cached properties using the current counting code (which was a work-around of lacking django support)
- [ ] Try out filtering cached properties by resurrecting a portion of the old (removed) refilter code.

**Comment by hepcat72** [comment]
Ugh... Hit a snag.  The hefty data test shows that this feature doesn't scale well.  These are the load times of a page of all peak data:

- without the stats added: 6 seconds
- with stats added and no duplicate root table row issue work-around (i.e. all root table recs unique): 17 seconds
- with stats added and with the work-around for duplicate root table rows: 51 seconds

So unless I can figure out a way to keep the search running efficiently (possibly only load stats when the stats button is clicked), I'm going to hold back on submitting this branch.  I might even set it aside and work on something else...

**Comment by mneinast** [comment]
I agree this would have to be a separate button click given time to
calculate. Although for many datasets that would not take super long.

**Comment by hepcat72** [comment]
I got the work-around version (the version that won't cause data-dependent errors) down to 36 seconds on "all data" (caveat: without the Corrected Abundances > 0.1 filter).

It's interesting that going the same thing in the shell runs in under 11 seconds (which I might consider an acceptable worst-case scenario if I were to limit that calculation to only the first page of results).
```
In [1]: from DataRepo.models import PeakData
   ...: from DataRepo.views import performQuery
   ...: import cProfile
   ...: cProfile.run('res, cnt, sts = performQuery(fmt="pdtemplate", limit=10)')
         5955606 function calls (5955422 primitive calls) in 10.933 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1726    0.007    0.000    0.269    0.000 compiler.py:1640(cursor_iter)
     1726    0.003    0.000    0.161    0.000 compiler.py:1646(<lambda>)
     1725    0.089    0.000    0.089    0.000 compiler.py:1647(<listcomp>)
       26    0.003    0.000    0.003    0.000 query.py:978(<listcomp>)
     1730    0.002    0.000    0.003    0.000 utils.py:21(__getattr__)
     1727    0.003    0.000    0.155    0.000 utils.py:95(inner)
        1    2.078    2.078    9.717    9.717 views.py:1055(getQueryStats)
  2931599    0.917    0.000    1.243    0.000 views.py:1103(<genexpr>)
    70210    0.018    0.000    0.018    0.000 views.py:1125(<lambda>)
        9    0.013    0.001    0.031    0.003 {built-in method builtins.sorted}
        1    0.001    0.001    0.001    0.001 {built-in method marshal.loads}
        1    0.010    0.010    0.010    0.010 {built-in method psycopg2._psycopg._connect}
        3    0.012    0.004    0.012    0.004 {method 'close' of 'psycopg2.extensions.cursor' objects}
        3    7.144    2.381    7.144    2.381 {method 'execute' of 'psycopg2.extensions.cursor' objects}
     1726    0.152    0.000    0.152    0.000 {method 'fetchmany' of 'psycopg2.extensions.cursor' objects}
  1552023    0.326    0.000    0.326    0.000 {method 'index' of 'list' objects}
  1379624    0.140    0.000    0.141    0.000 {method 'join' of 'str' objects}
```
There may be ways to cut some more corners... I'll have to think about it some more...

**Comment by mneinast** [comment]
Would it save time to NOT calculate the measured values here?  Instead only
do this for metadata?

**Comment by hepcat72** [comment]
No, I don't think so.  I doubt I'll even see it in the profiling stats, but it will be included those stats, so if it does take time, I'll see it.  I'm currently writing the code that will only calculate the stats when the stats button is clicked.  It will essentially perform the page load again, so if you don't click the stats, the load time will be what you see currently without any stats.

**Comment by hepcat72** [comment]
Well, I don't know what the 13 second load was all about. Must have been some sort of caching fluke.  I can't even seem to predict how long it's going to take.  Worst case (browsing all peakdata) can still take 51 seconds, but I did it just now and it took 16. 🙄

Either way, I couldn't help but work on this to separate the stats load from the results page load.  Now the first time you click the stats button (currently on each page of results), it immediately shows you a "compiling stats" message and then the page reloads with the stats.  Here's a small search result example:

![statsimprovement](https://user-images.githubusercontent.com/2300532/159579256-792a3534-ff65-41e2-8407-c295b910d113.gif)

The gif starts only a fraction of a second before clicking the stats button, but you can see the message about it taking a few seconds...

I still have some work to do, but I thought I would post a status.

**Comment by mneinast** [comment]
This seems great!  It could be implemented and then we just wait for
feedback to see real-world load times.

**Comment by hepcat72** [comment]
Today was somewhat of a wash - so much time in meetings and dealing with emails... but I *did* implement the filtering criteria.  In fact, it can trivially handle complex filters that are defined in the exact same underlying way as the advanced search interface, allowing multiple fields to be included in the filter.  E.g., say you wanted to count the number of carbon's whose count was greater than 3 - *can do*.  The last feature I want to add (barring the cached property stuff - which might change in the upcoming schema changes) is to pass the stats around from page to page once they're computed, so that changing pages of results from 1 search won't trigger another wait if you click the stats button...
