### ISSUE TITLE
Multiple Label and Multiple Tracer Support

### ISSUE THREAD

**Issue by mneinast** [Princeton-LSI-ResearchComputing/tracebase#364]
### Feature Inspiration

Many datasets generated by the lab utilize some combination of multiple labeled elements per tracer and multiple tracer compounds per animal. TraceBase must be able to store this type of data and perform at least basic computation and export. Currently, each animal has a single tracer with a single element labeled.

### Feature Description

**NOTE:** This is a high level task list issue to keep track of smaller sub-tasks. For now, only a few items have been fleshed out, but I will continue to create smaller, more detailed issues and link them here in place of the bullet points and notes.

- [ ] Update data model
    - [x] #390 
    - [x] #391
    - [x] Review, discuss, and come to consensus on data model
    - [x] #406 
    - [x] #408
- [x] Updating data loading commands
    - [x] #400
    - [x] #407 
    - [x] #444
    - [x] #427 
    - [x] #430
    - [x] #478 
- [ ] Update search and views
    - Multiple Labeled Data
        - [x] #393
        - [x] #394
        - [x] #395
    - Multiple Tracer Data
        - [x] #396
        - [x] #397
        - [x] #398

### Comment

Currently, the raw data from these experiments is not from Accucor.  It is instead generated by IsocorrCN  #349 

## Strategy

Implement change in model, then loader, then views, then search. The downstream parts **will break**, but merge each piece as we go.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

 -

**Comment by mneinast** [comment]
@fkang-pu  Here is an example of a dataset where some animals were infused with `[13C5, 15N2]-glutamine` or `[13C3, 15N1]-alanine`:
https://drive.google.com/drive/folders/1HwC647NBvZONdGce7uUOHyRCRg0EBRX0?usp=sharing

**Comment by lparsons** [comment]
NOTE: This is a high level task list issue to keep track of smaller sub-tasks. For now, only a few items have been fleshed out, but I will continue to create smaller, more detailed issues and link them here in place of the bullet points and notes.

**Comment by lparsons** [comment]
Moved #390 to the next milestone. I think this can be closed now.
